util-jvm: Check MaxHeapFreeRatio writable before writing
Problem

OptsTest doesn't build locally, because:

javax.management.RuntimeMBeanException: java.lang.IllegalArgumentException:
VM Option "MaxHeapFreeRatio" is not writeable

Solution

Check whether "MaxHeapFreeRatio" is writable.

RB_ID=565194

(sapling split of 9c83fdfb4bd43eeba154e9e5e4208f6be6006cc6)